version: '3.8'

services:
  expenseservice:
    build:
      context: ./ExpenseService
    ports:
      - "8080:80"
    volumes:
      - ./ExpenseService/expenses.db:/app/expenses.db
    networks:
      - expense-net

  reportservice:
    build:
      context: ./ReportService
    depends_on:
      - expenseservice
    ports:
      - "8081:81"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - expense-net

networks:
  expense-net:
    driver: bridge
